import React, { useState } from "react";
import {
  FaFolder,
  FaFolderOpen,
  FaFile,
  FaChevronRight,
  FaChevronDown,
  FaSitemap,
} from "react-icons/fa";

const TreeNode = ({ node, level = 0 }) => {
  const [expanded, setExpanded] = useState(true);

  const isFolder = node.type === "folder";
  const hasChildren =
    node.children && node.children.length > 0;

  return (
    <div>
      <div
        className="
          flex items-center gap-2
          py-2 px-2
          rounded-lg
          hover:bg-gray-50
          transition
        "
        style={{
          paddingLeft: `${level * 20 + 8}px`,
        }}
      >
        {isFolder && hasChildren ? (
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-gray-500"
          >
            {expanded ? (
              <FaChevronDown size={12} />
            ) : (
              <FaChevronRight size={12} />
            )}
          </button>
        ) : (
          <div className="w-3" />
        )}

        {isFolder ? (
          expanded ? (
            <FaFolderOpen className="text-yellow-500" />
          ) : (
            <FaFolder className="text-yellow-500" />
          )
        ) : (
          <FaFile className="text-blue-500" />
        )}

        <span className="font-medium text-gray-800">
          {node.name}
        </span>

        {node.description && (
          <span className="text-sm text-gray-400">
            — {node.description}
          </span>
        )}
      </div>

      {expanded &&
        hasChildren &&
        node.children.map((child, index) => (
          <TreeNode
            key={`${child.name}-${index}`}
            node={child}
            level={level + 1}
          />
        ))}
    </div>
  );
};

const FolderStructure = ({ structure }) => {
  if (!structure) {
    return (
      <div className="bg-white rounded-2xl border border-gray-200 p-6">
        <p className="text-gray-400">
          No folder structure available.
        </p>
      </div>
    );
  }

  const rootNodes = [];

  if (
    structure.frontend &&
    structure.frontend.length > 0
  ) {
    rootNodes.push({
      name: "frontend",
      type: "folder",
      description: "Frontend Application",
      children: structure.frontend,
    });
  }

  if (
    structure.backend &&
    structure.backend.length > 0
  ) {
    rootNodes.push({
      name: "backend",
      type: "folder",
      description: "Backend Application",
      children: structure.backend,
    });
  }

  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm">
      {/* Header */}
      <div className="flex items-center justify-between p-6 border-b border-gray-200">
  <div className="flex items-center gap-3">
    <div
      className="
        w-11 h-11
        rounded-xl
        bg-linear-to-br
        from-blue-600
        to-indigo-600
        flex
        items-center
        justify-center
        shadow-sm
      "
    >
      <FaSitemap className="text-white" />
    </div>

    <div>
      <h2 className="text-2xl font-bold text-gray-900">
        Folder Structure
      </h2>

      <p className="text-sm text-gray-500">
        Recommended project architecture generated by AI
      </p>
    </div>
  </div>

  <div className="hidden sm:flex flex-col items-end">
    <span className="text-2xl font-bold text-gray-900 leading-none">
      {rootNodes.length}
    </span>

    <span className="text-xs text-gray-400 font-medium uppercase tracking-wide mt-1">
      Modules
    </span>
  </div>
</div>

      {/* Tree */}
      <div className="p-4">
        {rootNodes.map((node, index) => (
          <TreeNode
            key={`${node.name}-${index}`}
            node={node}
          />
        ))}
      </div>
    </div>
  );
};

export default FolderStructure;